# Jason Lee - Week 5 Homework

1. Pandas stands for either **<ins>Panel Data<ins>**, or **<ins>Python Data Analysis<ins>**.
2. Pandas uses two collection types, **<ins>Series<ins>**, and **<ins>DataFrames<ins>**.
3. Four things Pandas can do for us: **<ins>loading and saving data<ins>**, **<ins>data fill<ins>**, **<ins>data cleansing<ins>**, and **<ins>data visualization<ins>**.
4. To permanently sort a DataFrame, one can use the **<ins>df.sort(inplace=False)<ins>**, or **<ins>df.sort(copy=True)<ins>** method, though these methods may be deprecated soon.  An alternative is to overwrite the dataframe like, **<ins>df = df.sort()<ins>**, or reassign the sorted data to a new dataframe like, **<ins>sorted_df = df.sort()<ins>**.
5. A CSV is a **<ins>Comma Separated Values<ins>** file.
6. When cleaning data we do not like **<ins>null<ins>** values, or **<ins>NaN (Not a Number)<ins>** values in our data.

---
7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- `.reshape()`

In [32]:
# Question 7
import numpy as np

# create a 12 element array
arrayX = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9,10], [11,12]])
print(np.shape(arrayX))

# reshape 12 element array to be (2, 3, 2)
arrayY = arrayX.reshape(2, 3, 2)
print(np.shape(arrayY))

(6, 2)
(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


---
8. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20

In [16]:
# Question 8
import numpy as np

# using .linspace() to make a list of 6 evenly spaced numbers between 0 and 20.
linear = np.linspace(0, 20, num=6)
print("Six evenly spaced numbers from 0 to 20:\n",linear)

Six evenly spaced numbers from 0 to 20:
 [ 0.  4.  8. 12. 16. 20.]


---
9. Make a Deep Copy of the above array

In [19]:
# Question 9
import numpy as np
import copy

# using .linspace() to make a list of 6 evenly spaced numbers between 0 and 20.
linear = np.linspace(0, 20, num=6)
deeplinear = copy.deepcopy(linear)
print("Six evenly spaced numbers from 0 to 20:\n",linear)
print("Deep copy of \"linear\":\n",deeplinear)

Six evenly spaced numbers from 0 to 20:
 [ 0.  4.  8. 12. 16. 20.]
Deep copy of "linear":
 [ 0.  4.  8. 12. 16. 20.]


---
10. Concatenate these 3 arrays into a new array named 'newArray'...
    ```python
            ([[25, 16]])
            ([[11, 2], [13, 4]])
            ([[7, 81], [5, 6], [11, 12]])
    ```

In [21]:
# Question 10
import numpy as np

arrayA = ([[25, 16]])
arrayB = ([[11, 2], [13, 4]])
arrayC = ([[7, 81], [5, 6], [11, 12]])

arrayX = np.concatenate((arrayA, arrayB, arrayC))
print("Concatenated array:\n",arrayX)

Concatenated array:
 [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


---
11. Sort 'newArray' in order into 'sortedArray'

In [ ]:
# Question 11
import numpy as np

arrayA = ([[25, 16]])
arrayB = ([[11, 2], [13, 4]])
arrayC = ([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((arrayA, arrayB, arrayC))
sortedArray = np.sort(newArray, axis= -1)

print("Concatenated array:\n",newArray)
print("\nSorted concatenated array:\n",sortedArray)

Concatenated array:
 [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]

Sorted concatenated array:
 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


---
12. Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.

In [36]:
# Question 12
import numpy as np

arrayA = ([[25, 16]])
arrayB = ([[11, 2], [13, 4]])
arrayC = ([[7, 81], [5, 6], [11, 12]])

# Bring the previous mess of arrays together
newArray = np.concatenate((arrayA, arrayB, arrayC))
# reshape the new array into 4 tuples
reshapedArray = newArray.reshape(4, -1)

# unpack array into 4 variables
tuple0, tuple1, tuple2, tuple3 = reshapedArray
print("Tuple0: ", tuple0)
print("Tuple1: ", tuple1)
print("Tuple2: ", tuple2)
print("Tuple3: ", tuple3)

Tuple0:  [25 16 11]
Tuple1:  [ 2 13  4]
Tuple2:  [ 7 81  5]
Tuple3:  [ 6 11 12]


---
13. Combine and sort the following arrays into one called 'comboArray' ...

    ```python
        one = ([10, 11, 12, 13, 14, 15, 16, 17])
        two = ([20, 21, 22, 23, 24, 25, 26, 27])
        three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
    ```

In [40]:
# Question 13
import numpy as np

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

# combine arrays
comboArray = np.concatenate((one, two, three))

# sort array
comboArray = np.sort(comboArray, axis= -1)

print("\nSorted and concatenated array:\n",comboArray)


Sorted and concatenated array:
 [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


---
14. Take 'comboArray' and perform the following slicing activities:
    - print sec1 - the 2nd element
    - print sec2 - all elements from the 3rd element to the last
    - print sec3 - all elements from the 4th to the 14th elements
    - print sec4 - the last 6 elements
    - print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
    - print sec6 - from #20 every even element to the end
    - print sec7 - from the last element moving forward, every 5th element.

In [57]:
# Question 14
import numpy as np

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

# combine arrays
comboArray = np.concatenate((one, two, three))

# sort array
comboArray = np.sort(comboArray, axis= -1)

print("\nSorted and concatenated array:\n",comboArray, "\n")
print("sec1: ",comboArray[1:2])
print("sec2: ",comboArray[2:])
print("sec3: ",comboArray[3:14])
print("sec4: ",comboArray[-6:])
print("sec5: ",comboArray[-27:15])
print("sec6: ",comboArray[20::2])
print("sec7: ",comboArray[27::-5])


Sorted and concatenated array:
 [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27] 

sec1:  [1]
sec2:  [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec3:  [ 3  4  5  6  7 10 11 12 13 14 15]
sec4:  [22 23 24 25 26 27]
sec5:  [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16]
sec6:  [24 26]
sec7:  [27 22 15 10  3]


---
15. Using `Series`, create a `DataFrame` that looks like this:

    | Ingredients | Quantity | Unit |
    |----|----|----|
    | Flour | 4 | cups |
    | Milk | 1 | cup |
    | Eggs | 2 | large |
    | Spam | 1 | can |

    Name: Dinner, dtype: object

In [95]:
# Question 15
import pandas as pd

ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name = 'Ingredients')
quantity = pd.Series([4, 1, 2, 1], name = 'Quantity')
unit = pd.Series(["cups", "cup", "large", "can"], name = "Unit")

dinner = pd.concat([ingredients, quantity, unit], axis = 1)

print(dinner)

  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


---
16. Take this data and create a DataFrame named studentData
    ```Python
        {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
    ```

In [ ]:
# Question 16
import pandas as pd

# The labor intensive way:
#Name = pd.Series(['Jai', 'janusha', 'Gaurav', 'Anuj'],  name = 'Name')
#Height = pd.Series([5.1, 6.2, 5.1, 5.2], name = 'Height')
#Qualification = pd.Series(['Msc', 'MA', 'Msc', 'Msc'], name = 'Qualification')
#address = pd.Series(['Delhi', 'Doha', 'Chennai', 'Dakhar'], name = 'address')
#Age = pd.Series([21, 23, 24, 21], name = 'Age')
#Pets = pd.Series(['Dog', 'Bunny', 'Chinchilla', 'Parrot'], name = 'Pets')
#sport = pd.Series(['Darts', 'Basketball', 'PaddleBoarding', 'Cricket'], name = 'sport')

#studentData = pd.concat([Name, Height, Qualification, address, Age, Pets, sport], axis=1)

# The easy way.
data = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }

studentData = pd.DataFrame(data)

print(studentData)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


---
17. Add a new column to the DataFrame with the following deserts:
        ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

In [ ]:
# Question 17
# to be run after previous code block

# The labor intensive way:
#deserts = pd.Series(["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"], name = 'deserts')

#studentData = pd.concat([Name, Height, Qualification, address, Age, Pets, sport, deserts], axis=1)

# Easy way:
deserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

studentData['deserts'] = deserts

print(studentData)

      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


---
18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

In [ ]:
# Question 18
# to be run after previous code block
studentData.sort_values(by = ['Name', 'address'], inplace = True, ascending = True)

print(studentData)

      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        deserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge  
150


---
19. Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:

    ```python
        df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
    ```

In [90]:
# Question 19
import pandas as pd

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

print(df)

df.to_csv('cows_and_goats.csv')

        Cows  Goats
Year 1    12     22
Year 2    20     19


---
20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

In [105]:
# Question 20 A
import pandas as pd

# setup the data
df = pd.DataFrame({'Carrots': [16, 27], 'Bell peppers': [4, 10]}, index=['Year 1', 'Year 2'])

# save the DataFrame to a file
df.to_csv('vegetables.csv')
print(df)

        Carrots  Bell peppers
Year 1       16             4
Year 2       27            10


In [ ]:
# Question 20 B
import pandas as pd

# read the data from the file
df2 = pd.read_csv('vegetables.csv', index_col=0)

# add a new vegetable
jalapenos = [4, 12]
df2['jalapenos'] = jalapenos

print(df2)

# save the DataFrame to a file
df.to_csv('vegetables2.csv')

        Carrots  Bell peppers  jalapenos
Year 1       16             4          4
Year 2       27            10         12
